#!/bin/bash

environment=$1

cmake_vars=""

if [[ $environment == "rpi" ]]; then
	echo "Building for 'rpi' environment..."
	cmake_vars="${cmake_vars} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAINS_PATH}/toolchain-rpi.cmake"
elif [[ $environment == "dev" ]]; then
	echo "Building for 'dev' environment..."
	echo "Getting toolchain information from system defaults..."
	cmake_vars="${cmake_vars} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAINS_PATH}/toolchain-amd64.cmake"
else
	echo "No environment specified! Exiting..."
	exit 1
fi

mkdir -p .cmake-build.d \
	&& rm -rf .cmake-build.d/* \
	&& cd .cmake-build.d \
	&& echo "Calling CMake..." \
	&& cmake ../ ${cmake_vars} \
	&& echo "Building app with Make..." \
	&& make \
	&& echo "Updating 'bin' dir..." \
	&& mv bin ${HOME}
