#!/bin/bash

environment=$1

cmake_vars=""

if [[ $environment == "arm32v7" ]]; then
	echo "Building for 'arm32v7' environment..."
	cmake_vars="${cmake_vars} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAINS_PATH}/toolchain-${TARGET_ENVIRONMENT}.cmake"
elif [[ $environment == "x64" ]]; then
	echo "Building for 'x64' environment..."
	echo "Getting toolchain information from system defaults..."
	cmake_vars="${cmake_vars} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAINS_PATH}/toolchain-${TARGET_ENVIRONMENT}.cmake"
else
	echo "No environment specified! Exiting..."
	exit 1
fi

mkdir -p .cmake-build.d \
	&& rm -rf .cmake-build.d/* \
	&& cd .cmake-build.d \
	&& echo "Calling CMake..." \
	&& cmake ../ ${cmake_vars} \
	&& echo "Building app with Make..." \
	&& make VERBOSE=1 \
	&& echo "Updating 'bin' dir..." \
	&& mv bin ${HOME}
