#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Script must be run as root user. Exiting..."
  exit 1
fi

apt-get -y install python-pip \
  && pip install docker-compose \
  && docker-compose -v \
  && echo "Success!"
