#!/bin/bash

if [[ $MODULE_NAME == "" ]]; then
  echo "MODULE_NAME variable not set!"
  exit 1
fi

if [[ $TARGET_ENVIRONMENT == "dev" ]]; then
   export TARGET_IMAGE="ubuntu:16.04"
elif [[ $TARGET_ENVIRONMENT == "rpi" ]]; then
  export TARGET_IMAGE="resin/raspberrypi3-debian"
else
  echo "Invalid target environment: '${TARGET_ENVIRONMENT}'."
  echo "Example: ./build-image dev"
  echo "Example: ./build-image rpi"
  exit 1
fi

echo "Building image 'monty-mod-${MODULE_NAME}-${TARGET_ENVIRONMENT}'..."
docker build \
  --no-cache \
  -t monty-mod-${MODULE_NAME}-${TARGET_ENVIRONMENT} \
  --build-arg TARGET_ENVIRONMENT=${TARGET_ENVIRONMENT} --build-arg TARGET_IMAGE=${TARGET_IMAGE} .
