#!/bin/bash

if [[ $MODULE_NAME == "" ]]; then
  echo "MODULE_NAME variable not set!"
  exit 1
fi

image_name="monty-mod-${MODULE_NAME}-rpi"
remote_host="tcp://rpi.local:2375"

temp_dir_path=$(mktemp -d)
echo "Saving tar into ${temp_dir_path}"

tar_image_path="${temp_dir_path}/${image_name}.tar"
echo "Saving image as tar file into ${tar_image_path}"
docker save -o ${tar_image_path} ${image_name}

echo "tar size: $(du -h ${tar_image_path})"

echo "Uploading '${image_name}.tar' via '${remote_host}'..."

docker -H ${remote_host} load -i ${tar_image_path}

echo "Cleaning up..." && rm -rf ${temp_dir_path}
