#!/bin/bash

lib_source_prefix="/deps/usr"
target_prefix="/usr"



echo "Moving libs from ${lib_source_prefix} to ${target_prefix}"
cp -r ${lib_source_prefix}/* ${target_prefix}

echo "Cleaning up..."
rm -rf ${lib_source_prefix}

echo "Running ldconfig..."
ldconfig
